- src/GSettingsBackend.c
- src/MakerDialogUtil.c
Debian uses -Werror=format-security by default, thus it cannot build
ibus-chewing without this modification.
> Fix format-security warnings

- src/GSettingsBackend.c
It is not safe to use generic integer format for fixed size integer,
expecially for int64, because usually "int64 != long int" on 32bit arch.
> Use GLib provided portable format macros for printf()

- src/MakerDialogUtil.c
It is troublesome to use "toupper" with "signed" char.
"g_ascii_toupper" is sufficient and easy for this case.
> Change to use GLib "g_ascii_toupper" instead of "toupper"

- src/MakerDialogProperty.c
Its function return type is boolean.
NULL is a pointer, not a boolean.
> Fix to return FALSE instead of NULL as failure

- test/IBusChewingPreEdit-test.c
* test/IBusChewingPreEdit-test.c:
1. correct the key name
2. check chi-eng-mode after pressing shift or caps lock.
> Fix testcase

- src/IBusChewingPreEdit.c
- test/IBusChewingPreEdit-test.c
* src/IBusChewingPreEdit.c:
if pre-edit buffer contains bopomofo, we have to call ESC
twice; one for bopomofo, one for the rest characters.
* test/IBusChewingPreEdit-test.c:
add test case for ibus_chewing_pre_edit_clear_pre_edit.
> Fix ibus_chewing_pre_edit_clear_pre_edit

- src/IBusChewingPreEdit.c
抱歉…
在 ``src/IBusChewingPreEdit.c`` 有行 ``{ IBUS_KEY_End, IBUS_KEY_Home, self_handle_end }`` 我想可能是筆誤，雖然不太確定，但我還是先修改了，另外還新增了 KP_Delete
> Fix Key Name

- src/IBusChewingPreEdit.c
- test/IBusChewingPreEdit-test.c
if "space to select" is enabled, chewing_handle_Space will
ignore the first space. Therefore, we use chewing_handle_Space
only when we want to select candidates.
* test/IBusChewingPreEdit-test.c
add test case
> Fix #79: Cannot input space when "space to select" is enabled

- src/IBusChewingPreEdit.c
- test/IBusChewingPreEdit-test.c
Althogh the pre-edit-buffer is empty, but users still need
up, down, left, right, page-up, page-down, backspace, and
escape key to close or turn pages of candidate list.
* test/IBusChewingPreEdit-test.c
add test case
> Fix #50: Cannot use Up, Left, PgUp, Ese etc. within "`" menu

- src/IBusChewingPreEdit.c
- src/IBusChewingPreEdit.h
- test/IBusChewingPreEdit-test.c
1. 和 libchewing 保持一致，切換英數模式時只清除預編區的注音符號，而非 force commit。
2. 為了只清除預編區的注音符號，新增 ``ibus_chewing_pre_edit_clear_bopomofo()``
3. 切換全形半形模式時應該可以不必更動預編區，但未免有其他預期外的問題，還是設定為清空注音符號
> Add ibus_chewing_pre_edit_clear_bopomofo()

- src/IBusChewingPreEdit.c
- test/IBusChewingPreEdit-test.c
1. Ctrol 鍵會觸發 ``EVENT_RESPONSE_IGNORE`` 和 ``force_commit``，導致無法使用 control + num 新增使用者詞彙，所以先將 force_commit 移除。
2. 用 control + 1 開啟符號清單來檢查 control + num 功能
> Fix #63: Cannnot add user-phrase via ctrl+num

- src/IBusChewingEngine-signal.c
根據 lantw44 的意見移除了 ``ibus_chewing_engine_focus_in`` 裡面的 ``commit_text`` ，移除後確實不會再刪除反白的文字了。
> Fix #53: Highlighted text will be cleared when switching windows

- src/IBusChewingUtil.c
``&asciiConst[]`` 似乎無法正確處理 ``IBUS_KP_0 ~ 9``，導致在 test case 一旦輸入 ``IBUS_KP_0 ~ 9`` 就會出錯，所以我將他們全部獨立列出。
> Let key_sym_get_name() recognize KP numbers

- src/IBusChewingProperties.c
如果沒錯的話，使用者不能自己隨意輸入選字鍵，只能從現有組合中挑選一種，但目前設定視窗裡的選擇清單看起來像是可以讓使用者自行輸入（如附圖），實際點選輸入區的話又會自動關閉，所以改成和『鍵盤排列』一樣。
> Modify dropdown menu for selecting keys

- src/IBusChewingPreEdit.c
Libchewing < 0.4.0 does not let user to control candidate list
with Backspace, PgUp and PgDn, therefore ibus-chewing should
provide these functions.
> Update self_handle_Backspace, PgUp & PgDn for compatibility

- src/IBusChewingApplier.c
- src/IBusChewingPreEdit.c
- src/IBusChewingProperties.c
- test/IBusChewingPreEdit-test.c
Eng-Mode: output numbers
Chi-Mode-default: output numbers
Chi-Mode-incomplete: no response
Selecting(selkeys are 1~0): select
Selecting(selkeys are NOT 1~0): no response
* src/IBusChewingProperties.c
remove "numpad-always-number"
* test/IBusChewingPreEdit-test.c
1. add test case
2. fix typo
> Fix #88: Use keypad to select candidates or input numbers directly

- src/IBusChewingApplier.c
- src/IBusChewingProperties.c
（1）使用者在設定預編區字數時多半不會想到輸入中的注音符號，就算想到也不知道該預留多少空位。
舉例來說，如果使用者想要預編區有 8 個字並且保持在可以選字的狀態，目前必須要自己加上 5。如果只 +4，輸入完第 8 字就會因為預編區額滿而送出字。
所以讓 ibus-chewing 幫使用者 +5，使用者就可以得到預期的結果。
（2）libchewing 內建詞庫的最長詞彙是 11 個字，所以預編區應該最少要容納 11 個字（不含輸入中的注音符號）。
> Tweak max max-chi-symbol-len

- src/IBusChewingPreEdit.c
- src/IBusChewingUtil.c
- test/IBusChewingPreEdit-test.c
1. 修復：用數字鍵盤輸入數字後不該切換成英文模式
2. 讓 ``key_sym_get_name()`` 和 ``keyHandlingRules[]`` 能處理數字盤上 0~9 以外的按鍵（加減乘除）
3. 修改數字鍵盤行為：組字到一半時按數字鍵盤會結束組字（清空未完成的ㄅㄆㄇ），然後輸入數字
4. 更新 test case
> Fix keypad

- src/IBusChewingEngine-signal.c
* 原本的設計似乎是打算讓組字中的ㄅㄆㄇㄈ顯示在 auxText，但是目前ㄅㄆㄇㄈ已經顯示在預編區，所以移除相關的程式碼。
* 實在不懂 ``ibus_chewing_engine_has_capabilite`` 的作用，但是它又會導致 auxText 停用，所以先移除了。目前還沒遇到異常狀況。
> Fix GitHub #85: Message of adding userphrase not displayed

- src/GSettingsBackend.c
- src/IBusChewingEngine-signal.c
- src/IBusChewingLookupTable.c
用 valgrind 分別跑 ``IBusChewingPreEdit-test`` 和 ``ibus-chewing-engine-test`` 兩個檔案，顯示四個地方有 definitely lost，移除 g_object_ref_sink() 或增補 unref 之後再跑一次就解除了。
IBusChewingPreEdit-test 修改前
```
==19740== LEAK SUMMARY:
==19740==    definitely lost: 241,088 bytes in 3,031 blocks
==19740==    indirectly lost: 136,279 bytes in 6,085 blocks
==19740==      possibly lost: 2,856 bytes in 28 blocks
==19740==    still reachable: 241,231 bytes in 1,980 blocks
==19740== ERROR SUMMARY: 134 errors from 134 contexts (suppressed: 0 from 0)
```
IBusChewingPreEdit-test 修改後
```
==14487== LEAK SUMMARY:
==14487==    definitely lost: 112 bytes in 2 blocks
==14487==    indirectly lost: 1,607 bytes in 29 blocks
==14487==      possibly lost: 2,824 bytes in 27 blocks
==14487==    still reachable: 241,222 bytes in 1,980 blocks …
```
> Fix memory leaks

- src/IBusChewingEngine-input-events.c
* src/IBusChewingEngine-input-events.c
index is a guit which cannot be less than zero.
> Remove comparison of unsigned enum expression < 0

- src/IBusChewingEngine-signal.c
- test/ibus-chewing-engine-test.c
1. 跑測試的時候出現程式記憶體區段錯誤 (core dumped)。似乎是不能用 ``self->auxText = 0`` 來清空，改用 ``ibus_text_new_from_static_string("")`` 就恢復正常了。
2. 現在 auxText 已經不顯示ㄅㄆㄇ，只顯示自訂詞彙的訊息（加入、已有），所以修改了 test case。
> Fix auxText and its test case

- src/IBusChewingPreEdit.c
* ibus_chewing_pre_edit_clear()
ibus_chewing_pre_edit_clear_pre_edit() calls ibus_chewing_pre_edit_update()
in the end. No need to call it again.
* ibus_chewing_pre_edit_clear_bopomofo()
update pre-edit buffer only when it is changed.
* ibus_chewing_pre_edit_force_commit()
currently no one calls it, except test cases. update comment.
> Tiny tuning

- src/IBusChewingPreEdit-private.h
- src/IBusChewingPreEdit.c
When a key is not needed by IM, it should return ignore on both
pressing and releasing.
* src/IBusChewingPreEdit-private.h
Add shortcut "ignore_when_buffer_is_empty_and_table_not_showing"
*  tweak indent
> Fix key handling

- src/main.c
1. ibus_engine_desc_new_varargs() 部份被 indent 排得太狹窄，反而影響閱讀，所以手動調整。
2. valgrind 顯示在 start_component() 有洩漏，使用 ``g_object_unref`` 來解除。
修改前：
```
（前略）
==9400== 838 (120 direct, 718 indirect) bytes in 1 blocks are definitely lost in loss record 6,241 of 6,369
==9400==    at 0x56833F3: g_type_create_instance (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1)
==9400==    by 0x5664DF7: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1)
==9400==    by 0x5665148: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1)
==9400==    by 0x56671B4: g_object_new_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1)
==9400==    by 0x508CA0C: ibus_component_new_varargs (in /usr/lib/x86_64-linux-gnu/libibus-1.0.so.5.0.511)
==9400==    by 0x508CAFF: ibus_component_new (in …
```
> Fix memory leak in start_component()

- test/ibus-chewing-engine-test.c
不曉得為什麼之前沒顯示錯誤…
目前 test case 似乎會使用既有的使用者詞庫，而非獨立的詞庫檔，使用者詞庫有可能已經包含測試用的詞，所以「加入：○○○」或「已有：○○○」兩種結果都有可能。
由於這邊只是要測試 aux 訊息有正確的顯示和清空，所以我把它改為檢查字數
> Update test cases for aux message

- src/IBusChewingEngine-input-events.c
- src/IBusChewingEngine.gob
When users set the property list (language bar) to "auto hide"
in ibus-setup, the bar will stick to the cursor and block the
candidats list, because ibus-chewing refreshes the bar on every
keystroke. Therefore, it's better to refresh the bar only when
users toggle Chi-Eng Mode or Shape Mode with Shift or Caps Lock.
> Refresh property list (language bar) only when needed

- src/IBusChewingEngine-input-events.c
- src/IBusChewingEngine-signal.c
- src/IBusChewingEngine.gob
- src/IBusChewingSystray.c
This commit contains the following modifications:
1. Fix: the property list (language bar) does not update when
toggling Chi/Eng Mode or Fullwidth/Halfwidth Shape via the
systray icon.
2. Add a setup button to the ibus indicator (and the language
bar), so that users can open the setup window more quickly.
In order to have consistent style with other buttons on
bar, use property symbol instead of icon.
3. Make the naming of prop_name more consistent:
"chiEng_prop", "alnumSize_prop", and "setup_prop".
4. Update property labels and tooltips.
> Update property list (language bar)

- src/IBusChewingEngine.gob
預編區額滿、自動送出的時候，預編區會看起來像是在閃爍。仔細觀察可發現，在按下按鍵、自動送出的那瞬間，預邊區的文字會消失，然後才又出現，這個現象在 chromium 的網址列特別明顯。
將 ``commit_text(self)`` 往前挪，這個現象就消失了。
> Update pre-edit and aux text after commit_text ()

- src/IBusChewingEngine.gob
I am not sure about this, I just give it a try and it seems to work.
Whenever users press ``Super+space`` or ``Ctrl+space`` to switch input methodes, ibus-chewing will be disabled, but the public IBusText *preEditText, *auxText and *outgoingText are not properly freed. Use ``g_object_unref`` to prevent leaking.
> Destroy *preEditText, *auxText and *outgoingText when disable

- src/IBusChewingEngine-input-events.c
- src/IBusChewingEngine-signal.c
- src/IBusChewingEngine.gob
- src/IBusChewingPreEdit-private.h
- src/IBusChewingPreEdit.c
- test/IBusChewingPreEdit-test.c
Some users take the temporary English mode as an alternative to disabling IM or
switching to default keyboard layout. For some some applications (e.g. games,
or the 注音 input tool in google translator), we'll need to let the key evets
pass directly, without being processed by ibus-chewing/libchwing.
Test cases update.
This should fix GitHub Issue #143, #144
> Ignore keystrokes in English mode

- src/IBusChewingEngine-signal.c
Double underline will be rendered as background colour in address bar
on Chrome Browser so that users cannot tell the cursor's position.
Disable this feature for now until we get a better solution.
> Stop marking interval with double underline

- src/IBusChewingApplier.c
- src/IBusChewingLookupTable.c
- src/IBusChewingPreEdit.c
- src/IBusChewingPreEdit.h
- src/IBusChewingProperties.c
- src/IBusChewingProperties.h
- test/IBusChewingPreEdit-test.c
* The settings from ibus-setup will be ignored in some Desktop Environment, so we need to add this option into the ibus-chewing setup.
* Fix undesired behavior from libchewing, let space key turns pages and switch length of the candidate list (#154).
* Make all turn-page-keys like arrow keys, space key, page down... etc. able to switch length of the candidate list.
* Update test case
> Support vertical lookup table and optimize turn page keys

- po/zh_TW.po
- src/IBusChewingApplier.c
- src/IBusChewingPreEdit-private.h
- src/IBusChewingPreEdit.c
- src/IBusChewingProperties.c
- src/IBusChewingProperties.h
- test/IBusChewingPreEdit-test.c
* Allowing Caps Lock and Shift as Chi-Eng-Mode toggle key at the same time often causes chaos during inputting and ruines user experience, so we use dropdown menu to simplify the use cases.
* Separate Shift-L and Shift-R as some users need.
* Update zh_TW translation
> Add dropdown menu for Chi-Eng-Mode toggle key

- CMakeLists.txt
- data/chewing.xml.in
> fix: configure path correctly

- CHANGELOG.md
- src/IBusChewingProperties.c
- src/IBusChewingUtil.h
- src/setup/ibus-setup-chewing-window.c
- src/setup/ibus-setup-chewing-window.ui
Add new layouts in `ibus-setup-chewing`, including:
* Carpalx
* Colemak-DH ANSI
* Colemak-DH Ortholinear
> Add Carpalx, Colemak-DH ANSI, and Colemak-DH Orth layout

- CHANGELOG.md
- src/ibus-chewing-engine.c
To avoid showing both the committed string and pre-edit buffer at the same time.
> refactor: Clear pre-edit buffer before commit

- src/IBusChewingProperties.c
- src/setup/org.freedesktop.IBus.Chewing.gschema.xml
Adding choices / value range to all string / integer type settings.
This change can allow users to do config through GSetting interface
directly, while prevent users from broken settings by themselves.
Example usage:
> feat: add value range to setting schema file

- .github/workflows/ci.yml
- CMakeLists.txt
- CMakePresets.json
- src/GSettingsBackend.c
- src/IBusChewingApplier.c
- src/IBusChewingLookupTable.c
- src/IBusChewingPreEdit.c
- src/ibus-chewing-engine.c
- src/main.c
- src/setup/ibus-setup-chewing-application.c
- src/setup/ibus-setup-chewing-window.c
- src/setup/main.c
- test/IBusChewingPreEdit-test.c
For motivation, see #206.
This PR contains commits for
- Upgrade from C99 to C23
- Turn on `-Wextra` and `-Werror` compiler options
- Fix corresponding errors
---
If desired, maybe I can extract the commit that upgrade to C23 as another PR.
Since that it's a standalone change to this project.
> Upgrade to C23 and adding more static check from compiler

- test/IBusChewingPreEdit-test.c
> test: Re-enable simple mode test

- src/IBusChewingPreEdit-private.h
- src/IBusChewingPreEdit.c
- src/ibus-chewing-engine.c
> Fix caps sync mode

- src/IBusChewingPreEdit.c
The current condition statement causes the down arrow key to function as a page turner in the vertical panel.
> Fix: Use Down Key to Select Candidates in Vertical Panel

- src/IBusChewingPreEdit.c
On GNOME 46 (and maybe earlier versions) with Wayland, the Ctrl+Space key event somehow cannot be passed to IBus correctly, which prevents users from switching input methods with that shortcut. 
As this event does not need to be handled by libchewing, we simply remove Ctrl from the modifiers for the self_handle_space function. This will ensure the event is always passed to IBus.
This should fix issue #253.
> Fix: Ensure Ctrl+Space Is Passed to IBus Correctly, Not Absorbed
